- name: Build Project
        run: |
          cd COOLTRACKVISION-main/Vision-Control/client
          # Мы копируем index.html из папки выше прямо перед билдом
          cp ../../index.html ./index.html
          npx vite build --root . --outDir dist
